const $=(selector,root=document)=>root.querySelector(selector);const $$=(selector,root=document)=>[...root.querySelectorAll(selector)];
const state={session:null,timer:null,settings:null,encoders:[],targets:{displays:[],windows:[],games:[]},devices:{inputs:[]},mode:'display',systemAudio:true,microphone:false,displayId:'primary',region:null,picker:null};
async function api(path,options){const response=await fetch(path,options);let body;try{body=await response.json()}catch{throw new Error(`引擎返回了无法解析的响应 (${response.status})`)}if(!response.ok||!body.ok)throw new Error(body.error||`请求失败 (${response.status})`);return body.data}
function showNotice(target,message,error=false){const node=$(target);node.textContent=message;node.classList.toggle('error',error);node.hidden=false;clearTimeout(node._timeout);node._timeout=setTimeout(()=>node.hidden=true,7000)}
function formatTime(seconds){seconds=Math.max(0,Math.floor(seconds||0));return [Math.floor(seconds/3600),Math.floor(seconds%3600/60),seconds%60].map(n=>String(n).padStart(2,'0')).join(':')}
function encoderName(id){return state.encoders.find(item=>item.id===id)?.name||id||'等待探测'}
function audioSummary(systemAudio,microphone){return `${systemAudio?'系统声开启':'系统声关闭'} · ${microphone?'麦克风开启':'麦克风关闭'}`}
function setSwitch(selector,on){$(selector).classList.toggle('on',on)}
function renderControls(){setSwitch('#system-audio-toggle',state.systemAudio);setSwitch('#microphone-toggle',state.microphone);$('#system-audio-label').textContent=state.systemAudio?'开启':'关闭';$('#microphone-label').textContent=state.microphone?'开启':'关闭';$$('.mode[data-mode]').forEach(button=>button.classList.toggle('active',button.dataset.mode===state.mode));$('#window-target-row').hidden=state.mode!=='window';$('#game-target-row').hidden=state.mode!=='game';$('#display-target-row').hidden=['window','game'].includes(state.mode);$('#region-target-row').hidden=state.mode!=='region';$('#region-summary').textContent=state.region?`${state.region.width} × ${state.region.height} · ${state.region.x}, ${state.region.y}`:'尚未框选'}
function renderSession(session){state.session=session;const active=session.state==='recording'||session.state==='paused',paused=session.state==='paused';$('.record-status').classList.toggle('recording',active);$('#status-title').textContent=paused?'录制已暂停':active?'正在录制':'准备就绪';$('#record-button').classList.toggle('recording',active);$('#record-button label').textContent=active?'停止并保存':'开始录制';$('#pause-button').hidden=!active;$('#pause-button').textContent=paused?'恢复':'暂停';$('#elapsed').textContent=formatTime(session.elapsed_seconds);const encoder=session.encoder_active||state.settings?.encoder;$('#home-encoder').textContent=state.mode==='audio_only'?'AAC':encoderName(encoder).replace('Software (','').replace(')','');const fallback=session.encoder_fallback?` · 已降级到 ${encoderName(session.encoder_active)}`:'';const target=active?session.target_summary:(state.mode==='audio_only'?'纯音频':state.mode==='window'?$('#window-target').selectedOptions[0]?.textContent:state.mode==='game'?$('#game-target').selectedOptions[0]?.textContent:state.mode==='region'?(state.region?`区域 ${state.region.width}×${state.region.height}`:'请选择区域'):$('#display-target').selectedOptions[0]?.textContent);$('#status-summary').textContent=`${target||'请选择目标'} · ${audioSummary(active?session.system_audio:state.systemAudio,active?session.microphone:state.microphone)}${active&&state.mode!=='audio_only'?` · ${encoderName(encoder)}`:''}${fallback}`}
async function refreshSession(){try{renderSession(await api('/api/v1/session'))}catch(error){showNotice('#notice',`无法连接本机引擎：${error.message}`,true)}}
async function toggleRecording(){const button=$('#record-button');button.disabled=true;try{if(['recording','paused'].includes(state.session?.state)){const result=await api('/api/v1/session/stop',{method:'POST'});renderSession(result);showNotice('#notice',`录制已保存并验证：${result.output_path}；${encoderName(result.encoder_active)}`);await loadLibrary()}else{if(!state.systemAudio&&!state.microphone)throw new Error('系统声和麦克风不能同时关闭');if(state.mode==='window'&&!$('#window-target').value)throw new Error('请先选择要录制的窗口');if(state.mode==='game'&&!$('#game-target').value)throw new Error('请先选择要捕获的游戏');if(state.mode==='region'&&!state.region)throw new Error('请先框选录制区域');const result=await api('/api/v1/session/start',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({mode:state.mode,display_id:state.displayId,region:state.mode==='region'?state.region:null,window_id:state.mode==='window'?$('#window-target').value:null,game_id:state.mode==='game'?$('#game-target').value:null,system_audio:state.systemAudio,microphone:state.microphone,mic_device_id:state.settings?.mic_device_id||'default',quality:'1080p30',encoder:state.settings?.encoder||'obs_x264'})});renderSession(result);if(result.warning)showNotice('#notice',result.warning);if(result.encoder_fallback)showNotice('#notice',`首选编码器失败，已降级到 x264：${result.fallback_reason}`,true)}}catch(error){showNotice('#notice',error.message,true)}finally{button.disabled=false}}
async function togglePause(){const pause=state.session?.state==='recording';try{renderSession(await api(`/api/v1/session/${pause?'pause':'resume'}`,{method:'POST'}))}catch(error){showNotice('#notice',error.message,true)}}
function humanSize(bytes){if(bytes<1024)return `${bytes} B`;if(bytes<1048576)return `${(bytes/1024).toFixed(1)} KB`;return `${(bytes/1048576).toFixed(1)} MB`}
function escapeHtml(value){return value.replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]))}
async function loadLibrary(){try{const items=await api('/api/v1/library');const list=$('#library-list');list.replaceChildren();$('#library-empty').hidden=items.length>0;$('.library-head').hidden=items.length===0;for(const item of items){const row=document.createElement('div');row.className='library-row';row.innerHTML=`<strong title="${escapeHtml(item.path)}">${escapeHtml(item.name)}</strong><span>${humanSize(item.size_bytes)}</span><span>${item.duration_seconds==null?'—':formatTime(item.duration_seconds)}</span><span>${new Date(item.modified_unix_seconds*1000).toLocaleDateString()}</span><button class="delete" data-id="${encodeURIComponent(item.id)}">删除</button>`;list.append(row)}}catch(error){showNotice('#library-notice',error.message,true)}}
async function deleteRecording(id){if(!confirm('确定删除这段录像？此操作无法撤销。'))return;try{await api(`/api/v1/library/${id}`,{method:'DELETE'});showNotice('#library-notice','录像已删除');await loadLibrary()}catch(error){showNotice('#library-notice',error.message,true)}}
async function loadEncoders(){const data=await api('/api/v1/encoders');state.encoders=data.encoders;const available=data.encoders.filter(item=>item.available);const unavailable=data.encoders.filter(item=>!item.available);$('#encoder').replaceChildren(...available.map(item=>new Option(`${item.name}${item.hardware?' · 硬件':''}`,item.id)));$('#unavailable-encoders').querySelector('p').textContent=unavailable.length?unavailable.map(item=>item.name).join('、'):'无'}
function fillWindowSelect(select,selected){select.replaceChildren(new Option('请选择窗口',''),...state.targets.windows.filter(item=>item.available).map(item=>new Option(`${item.title} — ${item.executable}`,item.id)));if(selected)select.value=selected}
function fillGameSelect(select,selected){select.replaceChildren(new Option('请选择游戏',''),...state.targets.games.filter(item=>item.available).map(item=>new Option(`${item.title} — ${item.executable}`,item.id)));if(selected)select.value=selected}
function fillDisplaySelect(select,selected){select.replaceChildren(...state.targets.displays.filter(item=>item.available).map(item=>new Option(`${item.name} · ${item.width}×${item.height}${item.primary?' · 主屏':''}`,item.id)));const id=selected==='primary'?state.targets.displays.find(item=>item.primary)?.id:selected;if(id)select.value=id}
async function loadTargets(){state.targets=await api('/api/v1/targets');fillWindowSelect($('#window-target'),state.settings?.window_id);fillWindowSelect($('#settings-window'),state.settings?.window_id);fillGameSelect($('#game-target'),state.settings?.game_id);fillGameSelect($('#settings-game'),state.settings?.game_id);fillDisplaySelect($('#display-target'),state.displayId);fillDisplaySelect($('#settings-display'),state.settings?.display_id);state.displayId=$('#display-target').value||state.targets.displays[0]?.id||'primary';renderSession(state.session||{})}
async function loadDevices(){state.devices=await api('/api/v1/devices/audio');$('#mic-device').replaceChildren(...state.devices.inputs.map(item=>new Option(item.name,item.id)));if(state.settings)$('#mic-device').value=state.settings.mic_device_id}
async function loadSettings(){const settings=await api('/api/v1/settings');state.settings=settings;state.mode=settings.capture_mode;state.systemAudio=settings.record_system_audio;state.microphone=settings.record_microphone;state.displayId=settings.display_id;state.region=settings.region;$('#output-directory').value=settings.output_directory;$('#quality').value=settings.quality;$('#encoder').value=settings.encoder;$('#capture-mode').value=settings.capture_mode;$('#settings-window').value=settings.window_id||'';$('#settings-game').value=settings.game_id||'';fillDisplaySelect($('#display-target'),settings.display_id);fillDisplaySelect($('#settings-display'),settings.display_id);state.displayId=$('#display-target').value||settings.display_id;$('#mic-device').value=settings.mic_device_id;setSwitch('#settings-system-audio',settings.record_system_audio);setSwitch('#settings-microphone',settings.record_microphone);renderControls();renderSession(state.session||{})}
async function saveSettings(event){event.preventDefault();try{const systemAudio=$('#settings-system-audio').classList.contains('on'),microphone=$('#settings-microphone').classList.contains('on'),mode=$('#capture-mode').value;if(!systemAudio&&!microphone)throw new Error('系统声和麦克风不能同时关闭');if(mode==='window'&&!$('#settings-window').value)throw new Error('窗口模式需要选择默认窗口');if(mode==='game'&&!$('#settings-game').value)throw new Error('游戏模式需要选择默认游戏');if(mode==='region'&&!state.region)throw new Error('区域模式需要先在录制页框选区域');state.settings=await api('/api/v1/settings',{method:'PUT',headers:{'content-type':'application/json'},body:JSON.stringify({output_directory:$('#output-directory').value.trim(),record_system_audio:systemAudio,record_microphone:microphone,capture_mode:mode,display_id:$('#settings-display').value,region:state.region,window_id:$('#settings-window').value||null,game_id:$('#settings-game').value||null,mic_device_id:$('#mic-device').value||'default',quality:$('#quality').value,encoder:$('#encoder').value,hotkey_start_stop:'Ctrl+Shift+R',hotkey_pause_resume:'Ctrl+Shift+P'})});state.mode=mode;state.displayId=state.settings.display_id;state.systemAudio=systemAudio;state.microphone=microphone;renderControls();renderSession(state.session||{});showNotice('#settings-notice','设置已保存到本机')}catch(error){showNotice('#settings-notice',error.message,true)}}
function route(){const name=location.hash==='#/library'?'library':location.hash==='#/settings'?'settings':'home';$$('[data-page]').forEach(page=>page.hidden=page.dataset.page!==name);$$('[data-route]').forEach(link=>link.classList.toggle('active',link.dataset.route===name));if(name==='library')loadLibrary()}
function selectedDisplay(){return state.targets.displays.find(item=>item.id===state.displayId)||state.targets.displays.find(item=>item.primary)}
async function pickNativeRegion(){const button=$('#pick-region');button.disabled=true;button.textContent='等待桌面框选…';try{const result=await api('/api/v1/region/pick',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({display_id:state.displayId})});state.region=result.region;state.displayId=result.display_id;state.settings=await api('/api/v1/settings');renderControls();renderSession(state.session||{});showNotice('#notice',`已选择 ${state.region.width} × ${state.region.height} 区域`)}catch(error){showNotice('#notice',`${error.message}；可使用“浏览器回退”。`,true)}finally{button.disabled=false;button.textContent='桌面框选'}}
function openBrowserRegionPicker(){const display=selectedDisplay();if(!display)return showNotice('#notice','没有可用显示器。',true);state.picker=null;$('#picker-display-name').textContent=`${display.name} · ${display.width} × ${display.height}`;$('#picker-selection').hidden=true;$('#confirm-region').disabled=true;$('#region-picker').hidden=false;document.body.classList.add('picking')}
function closeRegionPicker(){document.body.classList.remove('picking');$('#region-picker').hidden=true}
function pickerPoint(event){const rect=$('#picker-stage').getBoundingClientRect();return{x:Math.max(0,Math.min(rect.width,event.clientX-rect.left)),y:Math.max(0,Math.min(rect.height,event.clientY-rect.top)),rect}}
$('#picker-stage').addEventListener('pointerdown',event=>{const p=pickerPoint(event);state.picker={start:p,current:p};event.currentTarget.setPointerCapture(event.pointerId);$('#picker-selection').hidden=false});
$('#picker-stage').addEventListener('pointermove',event=>{if(!state.picker)return;state.picker.current=pickerPoint(event);const a=state.picker.start,b=state.picker.current,left=Math.min(a.x,b.x),top=Math.min(a.y,b.y),width=Math.abs(a.x-b.x),height=Math.abs(a.y-b.y),box=$('#picker-selection');Object.assign(box.style,{left:`${left}px`,top:`${top}px`,width:`${width}px`,height:`${height}px`});box.querySelector('span').textContent=`${Math.round(width)} × ${Math.round(height)}`;$('#confirm-region').disabled=width<12||height<12});
$('#picker-stage').addEventListener('pointerup',event=>event.currentTarget.releasePointerCapture(event.pointerId));
$('#confirm-region').addEventListener('click',()=>{const display=selectedDisplay(),a=state.picker.start,b=state.picker.current,rect=a.rect,left=Math.min(a.x,b.x),top=Math.min(a.y,b.y);let width=Math.round(Math.abs(a.x-b.x)/rect.width*display.width)&~1,height=Math.round(Math.abs(a.y-b.y)/rect.height*display.height)&~1;const x=display.x+(Math.round(left/rect.width*display.width)&~1),y=display.y+(Math.round(top/rect.height*display.height)&~1);width=Math.min(width,display.x+display.width-x)&~1;height=Math.min(height,display.y+display.height-y)&~1;if(width<32||height<32)return;state.region={x,y,width,height};closeRegionPicker();renderControls();renderSession(state.session||{})});
$('#cancel-region').addEventListener('click',closeRegionPicker);$('#pick-region').addEventListener('click',pickNativeRegion);$('#pick-region-browser').addEventListener('click',openBrowserRegionPicker);
$$('.mode:not(.locked)').forEach(button=>button.addEventListener('click',()=>{state.mode=button.dataset.mode;renderControls();renderSession(state.session||{})}));$$('.mode.locked').forEach(button=>button.addEventListener('click',()=>showNotice('#notice',`${button.querySelector('span').textContent}模式尚未接入。`,true)));
function toggleAudio(key){const other=key==='systemAudio'?'microphone':'systemAudio';if(state[key]&&!state[other])return showNotice('#notice','至少保留系统声或麦克风中的一个。',true);state[key]=!state[key];renderControls();renderSession(state.session||{})}
$('#system-audio-toggle').addEventListener('click',()=>toggleAudio('systemAudio'));$('#microphone-toggle').addEventListener('click',()=>toggleAudio('microphone'));$('#settings-system-audio').addEventListener('click',event=>event.currentTarget.classList.toggle('on'));$('#settings-microphone').addEventListener('click',event=>event.currentTarget.classList.toggle('on'));$('#refresh-windows').addEventListener('click',loadTargets);$('#refresh-games').addEventListener('click',loadTargets);$('#window-target').addEventListener('change',()=>renderSession(state.session||{}));$('#game-target').addEventListener('change',()=>renderSession(state.session||{}));$('#display-target').addEventListener('change',event=>{state.displayId=event.target.value;state.region=null;renderControls();renderSession(state.session||{})});$('#record-button').addEventListener('click',toggleRecording);$('#pause-button').addEventListener('click',togglePause);$('#library-list').addEventListener('click',event=>{const button=event.target.closest('.delete');if(button)deleteRecording(button.dataset.id)});$('#open-folder').addEventListener('click',async()=>{try{await api('/api/v1/library/open',{method:'POST'})}catch(error){showNotice('#library-notice',error.message,true)}});$('#settings-form').addEventListener('submit',saveSettings);window.addEventListener('hashchange',route);window.lumaNavigate=name=>{location.hash=name==='settings'?'#/settings':name==='library'?'#/library':'#/'};
route();Promise.all([loadEncoders(),loadTargets(),loadDevices()]).then(loadSettings).then(refreshSession).catch(error=>showNotice('#notice',error.message,true));state.timer=setInterval(refreshSession,1000);
