const $=(selector,root=document)=>root.querySelector(selector);const $$=(selector,root=document)=>[...root.querySelectorAll(selector)];
const state={session:null,timer:null,settings:null,encoders:[]};
async function api(path,options){const response=await fetch(path,options);let body;try{body=await response.json()}catch{throw new Error(`引擎返回了无法解析的响应 (${response.status})`)}if(!response.ok||!body.ok)throw new Error(body.error||`请求失败 (${response.status})`);return body.data}
function showNotice(target,message,error=false){const node=$(target);node.textContent=message;node.classList.toggle('error',error);node.hidden=false;clearTimeout(node._timeout);node._timeout=setTimeout(()=>node.hidden=true,6000)}
function formatTime(seconds){seconds=Math.max(0,Math.floor(seconds||0));return [Math.floor(seconds/3600),Math.floor(seconds%3600/60),seconds%60].map(n=>String(n).padStart(2,'0')).join(':')}
function encoderName(id){return state.encoders.find(item=>item.id===id)?.name||id||'等待探测'}
function renderSession(session){state.session=session;const recording=session.state==='recording';$('.record-status').classList.toggle('recording',recording);$('#status-title').textContent=recording?'正在录制':'准备就绪';$('#record-button').classList.toggle('recording',recording);$('#record-button label').textContent=recording?'停止并保存':'开始录制';$('#elapsed').textContent=formatTime(session.elapsed_seconds);const encoder=session.encoder_active||state.settings?.encoder;$('#home-encoder').textContent=encoderName(encoder).replace('Software (','').replace(')','');const fallback=session.encoder_fallback?` · 已降级到 ${encoderName(session.encoder_active)}`:'';$('#status-summary').textContent=recording?`主显示器 · 系统声正在写入 · ${encoderName(encoder)}${fallback}`:`主显示器 · 1920 × 1080 · 系统声开启 · 麦克风关闭${fallback}`}
async function refreshSession(){try{renderSession(await api('/api/v1/session'))}catch(error){showNotice('#notice',`无法连接本机引擎：${error.message}`,true)}}
async function toggleRecording(){const button=$('#record-button');button.disabled=true;try{if(state.session?.state==='recording'){const result=await api('/api/v1/session/stop',{method:'POST'});renderSession(result);const detail=result.encoder_fallback?`；硬编失败，已降级：${result.fallback_reason}`:`；编码器：${encoderName(result.encoder_active)}`;showNotice('#notice',`录制已保存并验证：${result.output_path}${detail}`);await loadLibrary()}else{const result=await api('/api/v1/session/start',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({mode:'display',system_audio:true,microphone:false,quality:'1080p30',encoder:state.settings?.encoder||'obs_x264'})});renderSession(result);if(result.encoder_fallback)showNotice('#notice',`首选编码器启动失败，已诚实降级到 x264：${result.fallback_reason}`,true)}}catch(error){showNotice('#notice',error.message,true)}finally{button.disabled=false}}
function humanSize(bytes){if(bytes<1024)return `${bytes} B`;if(bytes<1048576)return `${(bytes/1024).toFixed(1)} KB`;return `${(bytes/1048576).toFixed(1)} MB`}
async function loadLibrary(){try{const items=await api('/api/v1/library');const list=$('#library-list');list.replaceChildren();$('#library-empty').hidden=items.length>0;$('.library-head').hidden=items.length===0;for(const item of items){const row=document.createElement('div');row.className='library-row';row.innerHTML=`<strong title="${escapeHtml(item.path)}">${escapeHtml(item.name)}</strong><span>${humanSize(item.size_bytes)}</span><span>${item.duration_seconds==null?'—':formatTime(item.duration_seconds)}</span><span>${new Date(item.modified_unix_seconds*1000).toLocaleDateString()}</span><button class="delete" data-id="${encodeURIComponent(item.id)}">删除</button>`;list.append(row)}}catch(error){showNotice('#library-notice',error.message,true)}}
function escapeHtml(value){return value.replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]))}
async function deleteRecording(id){if(!confirm('确定删除这段录像？此操作无法撤销。'))return;try{await api(`/api/v1/library/${id}`,{method:'DELETE'});showNotice('#library-notice','录像已删除');await loadLibrary()}catch(error){showNotice('#library-notice',error.message,true)}}
async function loadEncoders(){try{const data=await api('/api/v1/encoders');state.encoders=data.encoders;const available=data.encoders.filter(item=>item.available);const unavailable=data.encoders.filter(item=>!item.available);const select=$('#encoder');select.replaceChildren(...available.map(item=>new Option(`${item.name}${item.hardware?' · 硬件':''}`,item.id)));$('#unavailable-encoders').querySelector('p').textContent=unavailable.length?unavailable.map(item=>item.name).join('、'):'无';if(state.settings)select.value=state.settings.encoder;renderSession(state.session||{})}catch(error){showNotice('#settings-notice',error.message,true)}}
async function loadSettings(){try{const settings=await api('/api/v1/settings');state.settings=settings;$('#output-directory').value=settings.output_directory;$('#quality').value=settings.quality;$('#encoder').value=settings.encoder;renderSession(state.session||{})}catch(error){showNotice('#settings-notice',error.message,true)}}
async function saveSettings(event){event.preventDefault();try{state.settings=await api('/api/v1/settings',{method:'PUT',headers:{'content-type':'application/json'},body:JSON.stringify({output_directory:$('#output-directory').value.trim(),record_system_audio:true,record_microphone:false,quality:$('#quality').value,encoder:$('#encoder').value})});renderSession(state.session||{});showNotice('#settings-notice','设置已保存到本机')}catch(error){showNotice('#settings-notice',error.message,true)}}
function route(){const name=location.hash==='#/library'?'library':location.hash==='#/settings'?'settings':'home';$$('[data-page]').forEach(page=>page.hidden=page.dataset.page!==name);$$('[data-route]').forEach(link=>link.classList.toggle('active',link.dataset.route===name));if(name==='library')loadLibrary();if(name==='settings')loadSettings()}
$$('.mode.locked').forEach(button=>button.addEventListener('click',()=>showNotice('#notice',`${button.querySelector('span').textContent}模式尚未接入，本版只支持主显示器全屏录制。`,true)));
$('#record-button').addEventListener('click',toggleRecording);$('#library-list').addEventListener('click',event=>{const button=event.target.closest('.delete');if(button)deleteRecording(button.dataset.id)});$('#open-folder').addEventListener('click',async()=>{try{await api('/api/v1/library/open',{method:'POST'})}catch(error){showNotice('#library-notice',error.message,true)}});$('#settings-form').addEventListener('submit',saveSettings);window.addEventListener('hashchange',route);window.lumaNavigate=name=>{location.hash=name==='settings'?'#/settings':name==='library'?'#/library':'#/'};
route();Promise.all([loadEncoders(),loadSettings()]).then(refreshSession);state.timer=setInterval(refreshSession,1000);
