const $=(selector,root=document)=>root.querySelector(selector);const $$=(selector,root=document)=>[...root.querySelectorAll(selector)];
const state={session:null,timer:null,settings:null,encoders:[],targets:{windows:[]},devices:{inputs:[]},mode:'display',systemAudio:true,microphone:false};
async function api(path,options){const response=await fetch(path,options);let body;try{body=await response.json()}catch{throw new Error(`引擎返回了无法解析的响应 (${response.status})`)}if(!response.ok||!body.ok)throw new Error(body.error||`请求失败 (${response.status})`);return body.data}
function showNotice(target,message,error=false){const node=$(target);node.textContent=message;node.classList.toggle('error',error);node.hidden=false;clearTimeout(node._timeout);node._timeout=setTimeout(()=>node.hidden=true,7000)}
function formatTime(seconds){seconds=Math.max(0,Math.floor(seconds||0));return [Math.floor(seconds/3600),Math.floor(seconds%3600/60),seconds%60].map(n=>String(n).padStart(2,'0')).join(':')}
function encoderName(id){return state.encoders.find(item=>item.id===id)?.name||id||'等待探测'}
function audioSummary(systemAudio,microphone){return `${systemAudio?'系统声开启':'系统声关闭'} · ${microphone?'麦克风开启':'麦克风关闭'}`}
function setSwitch(selector,on){$(selector).classList.toggle('on',on)}
function renderControls(){setSwitch('#system-audio-toggle',state.systemAudio);setSwitch('#microphone-toggle',state.microphone);$('#system-audio-label').textContent=state.systemAudio?'开启':'关闭';$('#microphone-label').textContent=state.microphone?'开启':'关闭';$$('.mode[data-mode]').forEach(button=>button.classList.toggle('active',button.dataset.mode===state.mode));$('#window-target-row').hidden=state.mode!=='window'}
function renderSession(session){state.session=session;const recording=session.state==='recording';$('.record-status').classList.toggle('recording',recording);$('#status-title').textContent=recording?'正在录制':'准备就绪';$('#record-button').classList.toggle('recording',recording);$('#record-button label').textContent=recording?'停止并保存':'开始录制';$('#elapsed').textContent=formatTime(session.elapsed_seconds);const encoder=session.encoder_active||state.settings?.encoder;$('#home-encoder').textContent=encoderName(encoder).replace('Software (','').replace(')','');const fallback=session.encoder_fallback?` · 已降级到 ${encoderName(session.encoder_active)}`:'';const target=recording?session.target_summary:(state.mode==='window'?$('#window-target').selectedOptions[0]?.textContent:'主显示器');$('#status-summary').textContent=`${target||'请选择窗口'} · ${audioSummary(recording?session.system_audio:state.systemAudio,recording?session.microphone:state.microphone)}${recording?` · ${encoderName(encoder)}`:''}${fallback}`}
async function refreshSession(){try{renderSession(await api('/api/v1/session'))}catch(error){showNotice('#notice',`无法连接本机引擎：${error.message}`,true)}}
async function toggleRecording(){const button=$('#record-button');button.disabled=true;try{if(state.session?.state==='recording'){const result=await api('/api/v1/session/stop',{method:'POST'});renderSession(result);showNotice('#notice',`录制已保存并验证：${result.output_path}；${encoderName(result.encoder_active)}`);await loadLibrary()}else{if(!state.systemAudio&&!state.microphone)throw new Error('系统声和麦克风不能同时关闭');if(state.mode==='window'&&!$('#window-target').value)throw new Error('请先选择要录制的窗口');const result=await api('/api/v1/session/start',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({mode:state.mode,window_id:state.mode==='window'?$('#window-target').value:null,system_audio:state.systemAudio,microphone:state.microphone,mic_device_id:state.settings?.mic_device_id||'default',quality:'1080p30',encoder:state.settings?.encoder||'obs_x264'})});renderSession(result);if(result.warning)showNotice('#notice',result.warning);if(result.encoder_fallback)showNotice('#notice',`首选编码器失败，已降级到 x264：${result.fallback_reason}`,true)}}catch(error){showNotice('#notice',error.message,true)}finally{button.disabled=false}}
function humanSize(bytes){if(bytes<1024)return `${bytes} B`;if(bytes<1048576)return `${(bytes/1024).toFixed(1)} KB`;return `${(bytes/1048576).toFixed(1)} MB`}
function escapeHtml(value){return value.replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]))}
async function loadLibrary(){try{const items=await api('/api/v1/library');const list=$('#library-list');list.replaceChildren();$('#library-empty').hidden=items.length>0;$('.library-head').hidden=items.length===0;for(const item of items){const row=document.createElement('div');row.className='library-row';row.innerHTML=`<strong title="${escapeHtml(item.path)}">${escapeHtml(item.name)}</strong><span>${humanSize(item.size_bytes)}</span><span>${item.duration_seconds==null?'—':formatTime(item.duration_seconds)}</span><span>${new Date(item.modified_unix_seconds*1000).toLocaleDateString()}</span><button class="delete" data-id="${encodeURIComponent(item.id)}">删除</button>`;list.append(row)}}catch(error){showNotice('#library-notice',error.message,true)}}
async function deleteRecording(id){if(!confirm('确定删除这段录像？此操作无法撤销。'))return;try{await api(`/api/v1/library/${id}`,{method:'DELETE'});showNotice('#library-notice','录像已删除');await loadLibrary()}catch(error){showNotice('#library-notice',error.message,true)}}
async function loadEncoders(){const data=await api('/api/v1/encoders');state.encoders=data.encoders;const available=data.encoders.filter(item=>item.available);const unavailable=data.encoders.filter(item=>!item.available);$('#encoder').replaceChildren(...available.map(item=>new Option(`${item.name}${item.hardware?' · 硬件':''}`,item.id)));$('#unavailable-encoders').querySelector('p').textContent=unavailable.length?unavailable.map(item=>item.name).join('、'):'无'}
function fillWindowSelect(select,selected){select.replaceChildren(new Option('请选择窗口',''),...state.targets.windows.filter(item=>item.available).map(item=>new Option(`${item.title} — ${item.executable}`,item.id)));if(selected)select.value=selected}
async function loadTargets(){state.targets=await api('/api/v1/targets');fillWindowSelect($('#window-target'),state.settings?.window_id);fillWindowSelect($('#settings-window'),state.settings?.window_id);renderSession(state.session||{})}
async function loadDevices(){state.devices=await api('/api/v1/devices/audio');$('#mic-device').replaceChildren(...state.devices.inputs.map(item=>new Option(item.name,item.id)));if(state.settings)$('#mic-device').value=state.settings.mic_device_id}
async function loadSettings(){const settings=await api('/api/v1/settings');state.settings=settings;state.mode=settings.capture_mode;state.systemAudio=settings.record_system_audio;state.microphone=settings.record_microphone;$('#output-directory').value=settings.output_directory;$('#quality').value=settings.quality;$('#encoder').value=settings.encoder;$('#capture-mode').value=settings.capture_mode;$('#settings-window').value=settings.window_id||'';$('#mic-device').value=settings.mic_device_id;setSwitch('#settings-system-audio',settings.record_system_audio);setSwitch('#settings-microphone',settings.record_microphone);renderControls();renderSession(state.session||{})}
async function saveSettings(event){event.preventDefault();try{const systemAudio=$('#settings-system-audio').classList.contains('on'),microphone=$('#settings-microphone').classList.contains('on'),mode=$('#capture-mode').value;if(!systemAudio&&!microphone)throw new Error('系统声和麦克风不能同时关闭');if(mode==='window'&&!$('#settings-window').value)throw new Error('窗口模式需要选择默认窗口');state.settings=await api('/api/v1/settings',{method:'PUT',headers:{'content-type':'application/json'},body:JSON.stringify({output_directory:$('#output-directory').value.trim(),record_system_audio:systemAudio,record_microphone:microphone,capture_mode:mode,display_id:'primary',window_id:$('#settings-window').value||null,mic_device_id:$('#mic-device').value||'default',quality:$('#quality').value,encoder:$('#encoder').value})});state.mode=mode;state.systemAudio=systemAudio;state.microphone=microphone;renderControls();renderSession(state.session||{});showNotice('#settings-notice','设置已保存到本机')}catch(error){showNotice('#settings-notice',error.message,true)}}
function route(){const name=location.hash==='#/library'?'library':location.hash==='#/settings'?'settings':'home';$$('[data-page]').forEach(page=>page.hidden=page.dataset.page!==name);$$('[data-route]').forEach(link=>link.classList.toggle('active',link.dataset.route===name));if(name==='library')loadLibrary()}
$$('.mode:not(.locked)').forEach(button=>button.addEventListener('click',()=>{state.mode=button.dataset.mode;renderControls();renderSession(state.session||{})}));$$('.mode.locked').forEach(button=>button.addEventListener('click',()=>showNotice('#notice',`${button.querySelector('span').textContent}模式尚未接入。`,true)));
function toggleAudio(key){const other=key==='systemAudio'?'microphone':'systemAudio';if(state[key]&&!state[other])return showNotice('#notice','至少保留系统声或麦克风中的一个。',true);state[key]=!state[key];renderControls();renderSession(state.session||{})}
$('#system-audio-toggle').addEventListener('click',()=>toggleAudio('systemAudio'));$('#microphone-toggle').addEventListener('click',()=>toggleAudio('microphone'));$('#settings-system-audio').addEventListener('click',event=>event.currentTarget.classList.toggle('on'));$('#settings-microphone').addEventListener('click',event=>event.currentTarget.classList.toggle('on'));$('#refresh-windows').addEventListener('click',loadTargets);$('#window-target').addEventListener('change',()=>renderSession(state.session||{}));$('#record-button').addEventListener('click',toggleRecording);$('#library-list').addEventListener('click',event=>{const button=event.target.closest('.delete');if(button)deleteRecording(button.dataset.id)});$('#open-folder').addEventListener('click',async()=>{try{await api('/api/v1/library/open',{method:'POST'})}catch(error){showNotice('#library-notice',error.message,true)}});$('#settings-form').addEventListener('submit',saveSettings);window.addEventListener('hashchange',route);window.lumaNavigate=name=>{location.hash=name==='settings'?'#/settings':name==='library'?'#/library':'#/'};
route();Promise.all([loadEncoders(),loadTargets(),loadDevices()]).then(loadSettings).then(refreshSession).catch(error=>showNotice('#notice',error.message,true));state.timer=setInterval(refreshSession,1000);
